(set! process-up-direction "+z")
(sdegeo:set-auto-region-naming OFF)
(sdegeo:create-rectangle (position 0 0 0) (position 1.0 0.5 0) "InAlAs" "pregion")
(sdegeo:create-rectangle (position 0 0.5 0)  (position 1 1.0 0) "InAlAs" "buffer")
(sdegeo:create-rectangle (position 0 1.0 0)  (position 1 1.5 0) "InGaAs" "abs")
(sdegeo:create-rectangle (position 0 1.5 0)  (position 1.0 1.8 0) "InAlAs" "charge")
(sdegeo:create-rectangle (position 0 1.8 0)  (position 1 2.1 0) "InAlAs" "multi")
(sdegeo:create-rectangle (position 0 2.1 0)  (position 1 2.6 0) "InAlAs" "nregion")
(sdedr:define-constant-profile "ppregion" "BoronActiveConcentration" -1e+19)
(sdedr:define-constant-profile "pbuffer" "BoronActiveConcentration" -7e+14)
(sdedr:define-constant-profile "pabs" "PhosphorusActiveConcentration" 7e+14)
(sdedr:define-constant-profile "pcharge" "BoronActiveConcentration" -3e+17)
(sdedr:define-constant-profile "pmulti" "PhosphorusActiveConcentration" 7e+14)
(sdedr:define-constant-profile "nnregion" "PhosphorusActiveConcentration" 2e+19)
(sdedr:define-constant-profile-region "ppregion" "ppregion" "pregion")
(sdedr:define-constant-profile-region "nnregion" "nnregion" "nregion")
(sdedr:define-constant-profile-region "pmulti" "pmulti" "multi")
(sdedr:define-constant-profile-region "pcharge" "pcharge" "charge")
(sdedr:define-constant-profile-region "pabs" "pabs" "abs")
(sdedr:define-constant-profile-region "pbuffer" "pbuffer" "buffer")
(sdegeo:define-contact-set "source" 4  (color:rgb 1 0 0 ) "##")
(sdegeo:define-contact-set "drain" 4  (color:rgb 0 0 1 ) "##")
(sdegeo:set-current-contact-set "source")
(sdegeo:define-2d-contact (list (car (find-edge-id (position 0.5 2.6  0)))) "source")
(sdegeo:set-current-contact-set "drain")
(sdegeo:define-2d-contact (list (car (find-edge-id (position 0.5 0 0)))) "drain")
(sdedr:define-refeval-window "device_mesh_win" "Rectangle"  (position -0.01 -0.01 0) (position 1.01 2.61 0))
(sdedr:define-refinement-size "DeviceMeshRefinementDefinition" 0.1 0.01 1E-2 1E-3 )
(sdedr:define-refinement-placement "full_area" "DeviceMeshRefinementDefinition" (list "window" "device_mesh_win" ) )
; ** higher mesh in the multi--------------------------------------------
(sdedr:define-refeval-window "multi_mesh_win" "Rectangle"  (position -0.01 1.49 0) (position 1.01 2.11 0))
(sdedr:define-refinement-size "MultiMeshRefinementDefinition" 0.1 1E-3 1E-3 1E-5 )
(sdedr:define-refinement-placement "full_area" "MultiMeshRefinementDefinition" (list "window" "multi_mesh_win" ) )
;--------------------------------------------------------------------
(sde:set-meshing-command "snmesh -a -c boxmethod")
(sdedr:append-cmd-file "")
(sde:save-model "/home/ndissanayake/synopsys/gainsaturation/toy/small-width-multi/narrow_charge_layer/inalas/doe-010623-control-e-avalanche/thinmultidiode")
(sde:build-mesh "snmesh" "-a -c boxmethod" "/home/ndissanayake/synopsys/gainsaturation/toy/small-width-multi/narrow_charge_layer/inalas/doe-010623-control-e-avalanche/thinmultidiode")
;(system:command "svisual /home/ndissanayake/synopsys/gainsaturation/toy/small-width-multi/narrow_charge_layer/inalas/doe-010623-control-e-avalanche/thinmultidiode_msh.tdr &")
